### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by pschatzmann**

### CODE REVIEW

**Comment by LinusHeu** [comment]
The latest commit (test workaround: make I2SRP2040 semi-blocking) is only for testing! 
See:
https://github.com/pschatzmann/arduino-audio-tools/issues/857#issuecomment-1569015422

**Comment by pschatzmann** [comment]
All the other I2S implementations for the other processors are also using a blocking API.
In order to make the reading work you will need to change the available() method to return a number. e.g. the buffer size.

**Comment by LinusHeu** [comment]
> All the other I2S implementations for the other processors are also using a blocking API.

Thank you. I didn't notice that. I thought this loop in StreamCopy was because the I2SStream/I2SDriver/etc was supposed to be non-blocking. However, it's only needed because StreamCopy can copy to any kind of stream and some streams could be non-blocking, right?
https://github.com/pschatzmann/arduino-audio-tools/blob/783ca5379636f05db65f710d587d54c6d2d0d062/src/AudioTools/StreamCopy.h#L277-L301
Just making write blocking makes it easier :D 

I haven't started implementing anything about read. But I will do that as soon as I have output working reliably.

**Comment by pschatzmann** [comment]
For I2S I went for the easiest solution: There might be some other output classes which might be non blocking and I keep things open to possibly change it in the future.

The feature-rp2040 has been merged, so I close this request

**Pull request closed without merging**
