### PR TITLE
Main

### PR DESCRIPTION
**Pull request by podaen**

### CODE REVIEW

**Comment by pschatzmann** [comment]
I don't think that void setUrlTimeout(int time) should be on this level because it is only relevant to AudioSourceURL

**Comment by pschatzmann** [comment]
However the following would make sense to me:
- rename the current setTimeoutMs() and timeoutMs() to setTimeoutAutoNextMs() timeoutAutoNextMs()
- rename setUrlTimeout() to setTimeout(). The setTimeout() method in Arduino is valid for any Stream...

**Comment by podaen** [comment]
I still having an issue on the not responding link like "http://mp3.streampower.be/sporza-high".  It woks after begin() but It will not go to the next one in the copier.

Here are the links I used

> 	"http://mp3.streampower.be/sporza-high",
> 	"https://22323.live.streamtheworld.com/TOPRETRO.mp3",//piching
> 	"http://mp3.streampower.be/sporza-high",
> 	"http://23553.live.streamtheworld.com:80/RADIO_2_VLAAMSBR_128.mp3",
> 	"http://20723.live.streamtheworld.com/QFOUTERADIO.mp3",

**Comment by podaen** [comment]
This is where I don't understand it anymore

In the URLStreamESP32.h

>         void begin(const char* urlStr, const char* acceptMime=nullptr, MethodID action=GET,  const char* reqMime="", const char*reqData="") {
>             LOGD(LOG_METHOD);
>             p_urlStream->begin(urlStr, acceptMime, action,reqMime, reqData );
>             taskStream.begin();
>         }

in the URLStream.h

> bool begin(const char* urlStr, const char* acceptMime=nullptr, MethodID action=GET,  const char* reqMime="", const char*reqData="") {
>             LOGI( "URLStream.begin %s",urlStr);
>             
>             url.setUrl(urlStr);
>             int result = -1;
> 
>             // optional: login if necessary
>             login();
> 
>             //request.reply().setAutoCreateLines(false);
>             if (acceptMime!=nullptr){
>                 request.setAcceptMime(acceptMime);
>             }
>             result = process(action, url, reqMime, reqData);
>             if (result>0){
>                 size = request.getReceivedContentLength();
>                 LOGI("size: %d", (int)size);
>                 if (size>=0){
>                     waitForData();
>                 }
>             }
>             active = result == 200;
>             return active;
>         }

p_urlStream. =bool begin() ??

**Comment by podaen** [comment]
I was on a wrong trail... I see now the timeout is set by default somewhere to 20000ms. And I was thinking it is set in the AudioSource to 500ms. Soo I was looking where it was hanging out... And it was the whole time in the copier. it's confusing with the 500ms. Where is the 20000ms set?

**Comment by pschatzmann** [comment]
In the constructor of AudioSourceURL - this is the default value for AudioSourceURL

**Comment by podaen** [comment]
Can we merge the default timeout_value of AudioSource and AudioSourceURL in to one variable?

**Comment by pschatzmann** [comment]
I am confused. We only have one variable.
Let me try to understand: timeout_value should actually be timeout_auto_next_value.
And we have the setTimeout() which sets the timeout of the stream.  These are two different concepts....

**Comment by podaen** [comment]
I know it can be set. Why it set to a value in the Audiosource to 500 and in the AudioSourceURL  to 20000?

**Comment by pschatzmann** [comment]
I think the AudioSourceURL is the only implementation which is slow. Any other - files, arrays, callbacks are very fast...

**Comment by podaen** [comment]
I is too long indeed. I will do some measurements to set the defauld value a litle more close to the slowest connection I have.

**Comment by pschatzmann** [comment]
Just add a big safety margin. You are on a fast network and maybe you should also double check a connection via the mobile phone...

**Comment by podaen** [comment]
Maybe we can impove the transmitting power. Take a look in esp_bt.h 

C:\Users\user\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\tools\sdk\include\bt

I am looking at...

esp_err_t esp_ble_tx_power_set(esp_ble_power_type_t power_type, esp_power_level_t power_level);

**Comment by pschatzmann** [comment]
No this is for ID3 Metadata which is part of the MP3 stream. If you want to access the parameters available in the http replay you can access them in the AudioSourceURL with actual_stream->httpRequest().reply().get("parameter-name")...

**Comment by podaen** [comment]
This is for WiFi

I found a topic about it on esp-idf
https://esp32.com/viewtopic.php?t=5359

it is within the esp_wifi.h...

But it only for transmitting.

**Pull request merged**
