### PR TITLE
Ability to not use URL source in Audioplayer

### PR DESCRIPTION
**Pull request by podaen**
note that _WIN32 is not in c++

//----------------
#if defined(__linux__) || defined(_WIN32) || defined(__APPLE__)
#define USE_URL_ARDUINO
#define IS_DESKTOP
#endif

#ifdef IS_DESKTOP
#define USE_URL_ARDUINO
#endif

### CODE REVIEW

**Comment by podaen** [comment]
> note that _WIN32 is not in c++
> 
> //---------------- #if defined(**linux**) || defined(_WIN32) || defined(**APPLE**) #define USE_URL_ARDUINO #define IS_DESKTOP #endif
> 
> #ifdef IS_DESKTOP #define USE_URL_ARDUINO #endif

The reason is that the compiler is running on windows and therefore is reconized by the intelsens. There are multieple solution to resolve this issue. It's a discussion on vscode. I'm thinking of upgrading to vs2022.

**Comment by pschatzmann** [comment]
Is the issue when you build for the desktop or for an ESP32 ?

**Comment by podaen** [comment]
ESP32

**Comment by podaen** [comment]
issue of definition of _WIN32 can be undone by added "#undef _WIN32" before the header.

**Pull request merged**
