### PR TITLE
Added Binning to BaseConverter

### PR DESCRIPTION
**Pull request by uutzinger**
Binning sums samples and optionally divides by the number of samples that were binned.
This will reduced the samples without discarding.

### CODE REVIEW

**Comment by uutzinger** [comment]
Thanks for your support.
I tested with 8,16,24 and 32 bit.
I ran with binning 4 samples and 64 samples.
It seems to work ok.

**Comment by uutzinger** [comment]
I am getting compilation errors now. Something is wrong with TDM and I think is not related to my code as I don't have/use cs42448:

```
c:\Users\uutzi\Documents\Arduino\libraries\arduino-audio-driver\src/Driver/cs42448/cs42448.h: In member function 'bool CS42448::setFormat()':
c:\Users\uutzi\Documents\Arduino\libraries\arduino-audio-driver\src/Driver/cs42448/cs42448.h:565:12: error: reference to 'TDM' is ambiguous
  565 |       case TDM:
      |            ^~~
In file included from c:\Users\uutzi\Documents\Arduino\libraries\arduino-audio-driver\src/Driver.h:3:
c:\Users\uutzi\Documents\Arduino\libraries\arduino-audio-driver\src/Common.h:130:3: note: candidates are: 'audio_driver::i2s_format_t audio_driver::TDM'
  130 |   TDM = 4,        /*!< set tdm format */
      |   ^~~
In file included from c:\Users\uutzi\Documents\Arduino\libraries\arduino-audio-tools\src/AudioI2S/I2SConfig.h:9,
                 from c:\Users\uutzi\Documents\Arduino\libraries\arduino-audio-tools\src/AudioI2S/I2SStream.h:8,
                 from c:\Users\uutzi\Documents\Arduino\libraries\arduino-audio-tools\src/AudioTools.h:73,
                 from C:\Users\uutzi\Documents\Arduino\ES8388_i2s_bin_serial\ES8388_i2s_bin_serial.ino:34:
c:\Users\uutzi\Documents\Arduino\libraries\arduino-audio-tools\src/AudioI2S/I2SConfigESP32V1.h:19:3: note:                 'audio_tools::I2SSignalType audio_tools::TDM'
   19 |   TDM

```

**Comment by pschatzmann** [comment]
I can reproduce your issue...

**Comment by pschatzmann** [comment]
I committed a correction to the audio-driver library

**Pull request merged**
