### PR TITLE
Sd and url player support

### PR DESCRIPTION
**Pull request by podaen**

### CODE REVIEW

**Comment by pschatzmann** [comment]
I am afraid that this solution is too project specific. We could work on a more generic solution or you can just store this class in your local project.

**Comment by podaen** [comment]
By making a .h file you mean?

**Comment by pschatzmann** [comment]
Yes - My having a local file that would be the cleanest solution. 

For a more generic solution
- we could add an additional parameter to the constructor of AudioPlayer for the buffer_size
- add a setAudioSource(AudioSource& source,  int bufferSize) method to the AudioPlayer which would allow to switch the player on the fly and would adjust buffer size if necessary.

**Comment by pschatzmann** [comment]
Would it also work if you move the empty constructor to the protected section ? 
I would prefer to avoid that anybody uses this and runs into a dead-end...

**Comment by podaen** [comment]
Done!

**Pull request merged**
