### PR TITLE
Spell correction

### PR DESCRIPTION
**Pull request by podaen**

### CODE REVIEW

**Comment by podaen** [comment]
Please confirm... Could we make a new folder for the player?

**Comment by pschatzmann** [comment]
I dont understand. Why would you need a new folder and where ?

**Comment by podaen** [comment]
I would place the player on a own subdirectory, out of the audiotools...

**Comment by pschatzmann** [comment]
You can just put it in the same directory where you have you ino sketch.

**Comment by podaen** [comment]
Just for me than?

**Comment by podaen** [comment]
I want to share it... And what if we placed under arduino-audio-tools/examples/examples-player/Multiplayer-sd-url. Is that ok for you?

**Comment by podaen** [comment]
if have created the file...

```
//MultiAudioPlayer.h
#include "AudioTools/AudioPlayer.h"

#ifndef _MultiAudioPlayer_h
#define _MultiAudioPlayer_h

#if defined(ARDUINO) && ARDUINO >= 100
	#include "arduino.h"
#else
	#include "WProgram.h"
#endif
namespace audio_tools {
	class MultiAudioPlayer : public AudioPlayer {
	public:
		MultiAudioPlayer() {
			LOGD(LOG_METHOD);
		}
		MultiAudioPlayer(AudioSource& SDsource, AudioSource& URLsource, AudioPrint& output, AudioDecoder& decoder) {
			LOGD(LOG_METHOD);
			this->p_SDsource = &SDsource;
			this->p_Urlsource = &URLsource;
			this->volume_out.begin(output);
			this->p_out_decoding = new EncodedAudioStream(volume_out, decoder);
			this->p_final_print = &output;
			// notification for audio configuration
			decoder.setNotifyAudioChange(*this);
		}
		/// Default destructor
		~MultiAudioPlayer() {
			if (p_out_decoding != nullptr) {
				delete p_out_decoding;
			}
		}
		virtual bool begin(int index = 0, bool isActive = true, bool isUrl = false, int bufferSize = 2048) {
			LOGD(LOG_METHOD);
			bool result = false;

			// set source
			if (isUrl == false) {
				setAudioSource(*p_SDsource, bufferSize);
			}
			else
			{
				setAudioSource(*p_Urlsource, bufferSize);
			}

			// navigation supoort
			autonext = p_source->isAutoNext();

			// start dependent objects
			p_out_decoding->begin();
			p_source->begin();
			meta_out.begin();

			if (index >= 0) {
				p_input_stream = p_source->selectStream(index);
				if (p_input_stream != nullptr) {
					if (meta_active) {
						copier.setCallbackOnWrite(decodeMetaData, this);
					}
					copier.begin(*p_out_decoding, *p_input_stream);
					timeout = millis() + p_source->timeoutAutoNext();
					active = isActive;
					result = true;
				}
				else {
					LOGW("-> begin: no data found");
					active = isActive;
					result = false;
				}
			}
			else {
				LOGW("-> begin: no stream selected");
				active = isActive;
				result = false;
			}
			return result;
		}
		/// Set source (SD or url)
		virtual void setAudioSource(AudioSource& source, int bufferSize) {
			#define DEFAULT_BUFFER_SIZE bufferSize
			this->p_source = &source;
		}
	protected:
		AudioSource* p_SDsource = nullptr;
		AudioSource* p_Urlsource = nullptr;
	};
}
#endif
```

**Pull request merged**
