### PR TITLE
Multi channel ESP32 continuous ADC

### PR DESCRIPTION
**Pull request by uutzinger**
There is issue with continuous ADC conversion on ESP32 with more than 2 channels:
**Data appears in scrambled order**
Singe channel and two channels work.

I am not sure if this an issue with `adc_continuous_read`,  buffer overrun in `readBytes()` routine in `AnalogDriverESP32v1` or just because of serial debug printing. If issue is with espressifs `adc_continuous_read` its likely hard to fix. I did not find examples for more than two channels with Espressif. 

Also I noticed that `StreamCopy` seems to have buffer size limit of 1024. If I set the buffer size to a larger value it caps it at 1024. This becomes a problem when the buffer size is not a multiple of number of channels. I made examples/test/adc/`read-esp32-multi-channel-csv` to test multiple channels. I am a little lost where the buffer is capped.

### CODE REVIEW

**Comment by pschatzmann** [comment]
I think the limit comes from the value that the available() method of AnalogDriverESP32V1 returns.

**Comment by uutzinger** [comment]
Thanks Phil, I will look into the` available` function.
Also I will look into sorting the incoming data from continuous ADC on EPS32.

**Comment by pschatzmann** [comment]
Try to take a new pull request...
I was rewriting the git history to decrease the size of the repository

**Comment by uutzinger** [comment]
I got some weird thing on my fork or several thousand commits ahead and behind. 
So I made a new fork.
I see that some of the changes I made are not included.
A small number of changes from others are also not included:
-  `.gitignore` is now much smaller 
- SandBox/ BLE ESP32 client and server code does not have  `AudiChange` in `info_char->registerFornotifyAudioChange(notifyCallback);` 
- 
I will include my previous changes in a future pull request. The other items you might need to decide.

**Comment by pschatzmann** [comment]
These were some commits from yesterday. 

I am not sure why your changes got lost. I was comparing the source code after the cleanup and did not find any differences.

**Pull request closed without merging**
