### PR TITLE
Parse Name By Path

### PR DESCRIPTION
**Pull request by podaen**
Alternative way to get a station name by path.

uses...

```
void loop() {
	player.copy();

	**if (source.pathReset() == true) {
		Serial.println(source.Path());**
	}
}
```

### CODE REVIEW

**Comment by pschatzmann** [comment]
Sorry, I have the feeling that this is way to complicated to be acceptable.  
Suggestions:  

- Remove the  resetPath() it is not necessary; 
- Remove the the resetPath(); Path() method calls in the navigation logic - : Instead just call urlPath=nullptr 
- Use small caps for method names 
- In the Path only redetermine it if it is null

I am not absolutely sure if I understand it correctly but with my Str class it would be something like
```
const char* path() {
  if (urlPath==nullptr){
		Str tmpStr(toStr());
		int pos = urlPath.lastIndexOf("/");
		if (pos>0){
			urlPath = urlPath[pos]+1;
		} else {
			// prevent nulls
			urlPath = "";
		}
  }
  return urlPath;
}

**Comment by podaen** [comment]
I don't know why but nothing seems to work with Str tmpStr(toStr());

The int pos = tmpStr.lastIndexOf("/"); is constant returning the the last.

and

tmpStr.substring(1, 10); doesn't work at all

**Comment by pschatzmann** [comment]
Can you give me a little bit more context ? what is the input string and the expected result ?
If you use your own subclass you could use the Arduino String operations which are easier to use...

**Comment by podaen** [comment]
> 		const char* path() {
> 			if (urlPath == nullptr) {
> 				Str tmpStr = toStr();
> 				tmpStr = tmpStr.c_str();
> 				//Serial.println(tmpStr.c_str());
> 				int pos = tmpStr.lastIndexOf("/");
> 				if (pos > 0) {
> 					//Serial.println(pos);
> 					//Serial.println(tmpStr.length());
> 					tmpStr.substring(pos, tmpStr.length());
> 				}
> 				else {
> 					// prevent nulls
> 					urlPath = "";
> 				}
> 			}
> 			return urlPath;
> 		}

**Comment by pschatzmann** [comment]
Was my initial proposal not working ? It was based on the fact that we just use the pointer the the existing string as result.

I think we should avoid the substring here because you would need to allocate first the resulting memory separatly.

**Comment by podaen** [comment]
nop, urlPath is nothing...

 if (urlPath==nullptr){
int pos = urlPath.lastIndexOf("/");

**Comment by pschatzmann** [comment]
```
const char* path() {
  if (urlPath==nullptr){
		Str tmpStr(toStr());
		int pos = tmpStr.lastIndexOf("/");
		if (pos>0){
			urlPath = &urlPath[pos+1];
		} else {
			// prevent nulls
			urlPath = "";
		}
  }
  return urlPath;
}
```

**Comment by podaen** [comment]
Having the same issues as mine...

**Comment by pschatzmann** [comment]
I am afraid I don't understand the problem. What is the data input vs output vs expected output ?

**Comment by podaen** [comment]
this is the problem

The int pos = tmpStr.lastIndexOf("/"); is constant returning the the last.

and

tmpStr.substring(1, 10); doesn't work at all

**Comment by pschatzmann** [comment]
I expect that it returns the last character when it ends with a "/" ...

**Comment by podaen** [comment]
no, I checked

**Comment by pschatzmann** [comment]
Can you send me the input data that you used to check so that I can run a test as well ?

**Comment by podaen** [comment]
I am wondering if this works in the audiosourcesdfat

/// checks if the file is a valid audio file
		bool isValidAudioFile(AudioFile& file) {
			file.getName(file_name, MAX_FILE_LEN);
			Str strFileName(file_name);
			bool result = strFileName.endsWith(exension) && strFileName.matches(file_name_pattern);
			LOGI("-> isValidAudioFile: '%s': %d", file_name, result);
			return result;
		}

**Comment by podaen** [comment]
"http://mp3.streampower.be/sporza-high",
	"https://22323.live.streamtheworld.com/TOPRETRO.mp3",//piching
	"http://mp3.streampower.be/sporza-high",

**Comment by pschatzmann** [comment]
Oops, Your right! There was a bug in lastIndexOf() and I never noticed.
I just committed a correction...

**Comment by podaen** [comment]
I think you have to check the substring too.

**Comment by pschatzmann** [comment]
Just made a test with 
  const char *url="http://mp3.streampower.be/sporza-high";
  Str str(url);
  int pos = str.lastIndexOf("/");
  Serial.println(url+pos+1);

which gives sporza-high

**Comment by pschatzmann** [comment]
No, it just does not do what you expect? It copies the content of the provided argument into the assigned memory location.  The usage pattern is 

char str[50];
String tmp(str);
tmp.substring("test",1,2);

now you have in str the values "es"

**Comment by podaen** [comment]
ok. I see now. I was confusing it with the String of the arduino

**Comment by podaen** [comment]
Yes I checked. it was from, start, end. You where right

**Comment by pschatzmann** [comment]
For the time being I want to avoid the Arduino Strings.
I am thinking of providing an plain vanilla IDF version that that would make it very difficult

**Comment by podaen** [comment]
Never heard of it

**Comment by pschatzmann** [comment]
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/index.html

Thats the framework which Arduino is based on for the ESP32...

**Comment by podaen** [comment]
haaa an other SDK

**Comment by pschatzmann** [comment]
fyi I have added an example how to extend the functionality with subclasses in an Arduino Sketch...

https://github.com/pschatzmann/arduino-audio-tools/tree/main/examples/examples-player/player-url_subclass-i2s

**Comment by podaen** [comment]
Hey, I was not done. Dit you test it... I get a backtrace of  tmpStr.substring("test", 1, 2); 

```
My test code

```
const char* path() {
			if (urlPath == nullptr) {
				Str tmpStr (toStr());

				//char str[50];
				//String tmp(str);
				//tmp.substring("test", 1, 2);

				//tmpStr = tmpStr.c_str();
				//Serial.println(tmpStr.c_str());
				//Str tmpStr = "temp/test";
				int pos = tmpStr.lastIndexOf("/");
				if (pos > 0) {
					//Serial.println(pos);
					//Serial.println(tmpStr.length());
					//urlPath = &(urlPath[size_t(pos)]);
					tmpStr.substring("test", 1, 2);
					//urlPath = urlPath;
					//urlPath = nullptr;
				}
				else {
					// prevent nulls
					urlPath = nullptr;
				}
			}
			return urlPath;
}
```

You can use your own links too.

why do you don't give any result on that procedure?
```
string temp = temp.substring("test", 1, 2); 
Serial.print(temp );
 "es"

**Comment by pschatzmann** [comment]
I have seen that you have removed all your logic, so I assumed that you decided to go with your own subclass. 
If you check my test from 2 h ago, it passed: Don't use substring but return toStr()+pos+1;

**Comment by podaen** [comment]
it doesn't make any sens. Serial.println(url+pos+1); 

if it would work like that it will give http://mp3.streampower.be/sporza-high27

**Comment by pschatzmann** [comment]
Here is my understanding:
- toStr() returns a unsinged char*  which is the actually selected url string e.g. "http://mp3.streampower.be/sporza-high"
- then you move the pointer by pos characters to the right so it will point to "/"
- +1 moves it past the found "/"

**Comment by podaen** [comment]
I know that... but it is not working to get the substring

**Comment by pschatzmann** [comment]
Ok, let me try - but just to double check. It is my understanding that you dont want a substring but just the end of the string after the last / ?
"http://mp3.streampower.be/sporza-high" should give "sporza-high" right ?

**Comment by podaen** [comment]
yeah, that's right.

**Comment by podaen** [comment]
if you get any result out of it

this will

```
		const char* path() {
			const char* tempStr = nullptr;
			if (urlPath == nullptr) {
				urlPath = toStr();
				//Serial.println(urlPath);
				size_t length = strlen(urlPath);  // find the string length
				for (size_t i = length - 1; i > 0; i--) {
					if (urlPath[i - 1] == '/') {
						//Serial.print(i);
						urlPath = &(urlPath[i]);
						break;
					}
				}
			}
			return urlPath;
}
```

**Comment by pschatzmann** [comment]
I extended by Subclassing Example with your case: 
https://github.com/pschatzmann/arduino-audio-tools/tree/main/examples/examples-player/player-url_subclass-i2s

In the log I am getting
```
16:16:43.369 -> [I] HttpHeader.h : 96 - HttpHeader::put -> 'Set-Cookie' : 'AISSessionId=5f9ea5422e2729b5_31979288_ry6NMlSS_MTg1Ljc0LjcwLjEz_0000009ShfJ; Path=/; Domain=centralcharts.ice.infomaniak.ch
16:16:43.369 -> [I] HttpHeader.h : 155 - HttpHeader::readLine -> 
16:16:43.403 -> [W] HttpRequest.h : 141 - no CONTENT_LENGTH found in reply
16:16:43.403 -> [I] URLStream.h : 72 - size: 0
16:16:43.403 -> [I] URLStream.h : 220 - Request written ... waiting for reply
16:16:43.896 -> icy name: Central Charts
16:16:43.896 -> Url name: centralcharts-128.mp3
16:16:44.213 -> [I] AudioCopy.h : 91 - StreamCopy::copy 1
```

**Comment by podaen** [comment]
I have looked at you example 

Can't find #include "AudioSourceIcyUrl.h"

source.icyName() and source.urlName()) is not a member of AudioSource

**Comment by pschatzmann** [comment]
It is part of the example! If you use the Arduino IDE just create it from the examples.
Otherwise you will need to add the additional custom implementation file as well...

**Comment by podaen** [comment]
I am not sure. This can't be AudioSourceIcyUrl.h

**Comment by pschatzmann** [comment]
yes it is

**Comment by podaen** [comment]
can you find it? https://github.com/pschatzmann/arduino-audio-tools/tree/main/src

**Comment by pschatzmann** [comment]
No it is part of the example ! Look again at

https://github.com/pschatzmann/arduino-audio-tools/tree/main/examples/examples-player/player-url_subclass-i2s

**Comment by pschatzmann** [comment]
The point is that we do not need to change the basic code to extend the functionality!

**Comment by podaen** [comment]
why not add it to the src code? It would be usefull to 

https://github.com/pschatzmann/arduino-audio-tools/tree/main/examples/examples-player/player-url-i2s

and what is this still doing in the shetch

void printMetaData(MetaDataType type, const char* str, int len){
  Serial.print("==> ");
  Serial.print(MetaDataTypeStr[type]);
  Serial.print(": ");
  Serial.println(str);
}

**Comment by podaen** [comment]
> and what is this still doing in the shetch
> 
> void printMetaData(MetaDataType type, const char* str, int len){ Serial.print("==> "); Serial.print(MetaDataTypeStr[type]); Serial.print(": "); Serial.println(str); }

For an mp3 stream. But all my links are mp3

**Comment by pschatzmann** [comment]
I was not convinced that this is useful enough and I thought it to be a good demo to show how to extend the functionality in an Arduino project.

But we can discuss...

**Comment by podaen** [comment]
I would leave it out and put it in an fat where it is usefull I think.

**Comment by podaen** [comment]
It is allready in there...

**Comment by podaen** [comment]
From one thing you would be allwase sure. The path will contain the information you want to have.

**Comment by pschatzmann** [comment]
I tend to disagree. I have seen plenty of URL which were basically just an IP address without path.
Can you file an issue for the printMetaData() so that I dont forget to look into this...

**Comment by podaen** [comment]
Yes, just iported localy the AudioSourceIcyUrl.h and it works even on moving to next. Soo thanks for that.

**Comment by podaen** [comment]
Could you please add the index of the stream to AudioSourceIcyUrl.h... I can't modifiy it because it is local.

**Comment by pschatzmann** [comment]
I am afraid I don't understand. 
It is a subclass of AudioSourceURL so the index() method is available as well...

**Comment by podaen** [comment]
True, I just had to catch it.

Serial.println(source.index());

I think I missing some

> Opening port
> Port open
> �.....
> [E] HttpRequest.h : 181 - Connect failed
> icy name: 
> Url name: sporza-high
> 0
> end setup
> [W] AudioPlayer.h : 618 - -> timeout - moving to next stream
> [W] HttpHeader.h : 225 - Waiting for data...
> [W] HttpRequest.h : 141 - no CONTENT_LENGTH found in reply
> Next Stream
> [E] HttpRequest.h : 181 - Connect failed
> [W] AudioPlayer.h : 618 - -> timeout - moving to next stream
> [W] HttpHeader.h : 225 - Waiting for data...
> [W] HttpRequest.h : 141 - no CONTENT_LENGTH found in reply
> icy name: Radio 2 – Vlaams Brabant
> Url name: RADIO_2_VLAAMSBR_128.mp3
> 3
> Next Stream
> [W] HttpHeader.h : 225 - Waiting for data...
> [W] HttpRequest.h : 141 - no CONTENT_LENGTH found in reply
> [E] URLStream.h : 224 - Error code recieved ... stop waiting for reply
> icy name: 
> Url name: QFOUTERADIO.mp3
> 4
> [W] AudioPlayer.h : 618 - -> timeout - moving to next stream
> [W] HttpHeader.h : 225 - Waiting for data...
> [W] HttpRequest.h : 141 - no CONTENT_LENGTH found in reply

Index 1 is missing...

**Comment by podaen** [comment]
Here is my list.. You will see
```

const char* urls[] = {
	"http://mp3.streampower.be/sporza-high",
	"https://22323.live.streamtheworld.com/TOPRETRO.mp3",//piching
	"http://mp3.streampower.be/sporza-high",
	"http://23553.live.streamtheworld.com:80/RADIO_2_VLAAMSBR_128.mp3",
	"http://20723.live.streamtheworld.com/QFOUTERADIO.mp3",
	"http://19983.live.streamtheworld.com/QMUSIC.mp3",
	"http://22183.live.streamtheworld.com/JOE.mp3",
	"http://21303.live.streamtheworld.com/STUDIO_BRUSSEL_128.mp3",
	"http://icecast-servers.vrtcdn.be/stubru_tgs-high.mp3",
	"http://icecast-servers.vrtcdn.be/stubru_tijdloze-high.mp3",
	"http://icecast-servers.vrtcdn.be/ketnetradio-high.mp3",
	"http://22353.live.streamtheworld.com/MNM_128.mp3",
	"http://icecast-servers.vrtcdn.be/mnm_90s00s-high.mp3",
	"http://icecast-servers.vrtcdn.be/mnm_hits-high.mp3",
	"http://icecast-servers.vrtcdn.be/mnm_urb-high.mp3",
	"http://fred.torontocast.com:1050/stream",
	"http://icecast-servers.vrtcdn.be/radio1_classics_high.mp3",
	"http://icecast-servers.vrtcdn.be/radio2_benebene-high.mp3",
	"http://icecast-servers.vrtcdn.be/radio2_unwind-high.mp3",
	"http://icecast-servers.vrtcdn.be/stubru_bruut-high.mp3",
	"http://icecast-servers.vrtcdn.be/stubru_untz-high.mp3"
	"http://23553.live.streamtheworld.com:80/RADIO_2_VLAAMSBR_128.mp3",
	"http://randstad.wirelessbelgie.be:8330/stream.mp3",
	"https://22323.live.streamtheworld.com/TOPRETRO.mp3",
	"http://21253.live.streamtheworld.com/RADIO1_128.mp3",
	"http://20723.live.streamtheworld.com/QFOUTERADIO.mp3",
	"http://23553.live.streamtheworld.com:80/RADIO_2_VLAAMSBR_128.mp3",
};
```

**Comment by podaen** [comment]
it is because printName(); is not called when moving to the next after a connect failed.

**Pull request merged**
