### PR TITLE
fast sine function Vbranch

### PR DESCRIPTION
**Pull request by vivichrist**
As requested a faster sine function

### CODE REVIEW

**Comment by pschatzmann** [comment]
Could you put this logic into a separate class ?

**Comment by vivichrist** [comment]
Yes and I did ask, just not here. The class will be Identical to SineWaveGenerator. So I guess I could use inheritance.

**Comment by vivichrist** [comment]
Ok, like so?

**Comment by pschatzmann** [comment]
Hmm, what is the reason for your change in SineWaveGenerator for the angle formula ? In C++ sine() will resolve to sinf() so it is my understanding that there is no performance advantage.

I propose to rename your fast sine() implementation to fast_sine() to make sure that there are no potential clashes. You could optionally also move it as static method to the FastSineGenerator class as well.

**Comment by pschatzmann** [comment]
Thanks a lot!

**Pull request merged**
